from fireNFX_Classes import *
#   PluginName:  Strum GS-2
#   ParamCount:  445
# -----------------------------------------------------------------
plStrumGS2 = TnfxChannelPlugin('Strum GS-2')
plStrumGS2.AlwaysRescan = False
plStrumGS2.addParamToGroup('ALL', TnfxParameter(0, 'Play Mode - Play Mode', 0, 'Guitar ', False, 2) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(1, 'Clock - Rate', 0, '90.00BPM ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(2, 'Mod Wheel - Vibrato Depth', 0, '51.6%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(3, 'Mod Wheel - Vibrato Speed', 0, '4.2Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4, 'Strumming - Auto', 0, 'Off ', False, 1) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(5, 'Strumming - Speed', 0, '31.8%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(6, 'Strumming - Velocity', 0, '0.00鐛ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(7, 'Voicing - Chord Type', 0, 'Movable ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(8, 'Voicing - Position', 0, 'Fret 1 ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(9, 'Loops - Loop Tempo', 0, 'Normal ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(10, 'Pick/Finger - Type', 0, 'Parabol ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(11, 'Pick/Finger - Position', 0, '14.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(12, 'Pick/Finger - Edge', 0, '79.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(13, 'Pick/Finger - Damping', 0, '39.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(14, 'Pick/Finger - Stiffness', 0, '37.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(15, 'Pick/Finger - Stiff Damp Velocity', 0, '5.00鐛ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(16, 'Pick/Finger - Depth', 0, '2.16mm ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(17, 'Pick/Finger - Speed', 0, '77.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(18, 'Pick/Finger - Speed Velocity', 0, '1.00鐛ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(19, 'String 1 - Tone A', 0, '99.4%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(20, 'String 1 - Inharmonicity A', 0, '12.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(21, 'String 1 - Decay A', 0, '53.7%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(22, 'String 1 - Tone B', 0, '51.1%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(23, 'String 1 - Inharmonicity B', 0, '18.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(24, 'String 1 - Decay B', 0, '89.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(25, 'String 1 - Coupling', 0, '19.8%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(26, 'String 1 - Balance', 0, '24.9%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(27, 'String 1 - Volume', 0, '-6.0dB ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(28, 'String 2 - Tone A', 0, '84.4%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(29, 'String 2 - Inharmonicity A', 0, '23.2%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(30, 'String 2 - Decay A', 0, '53.7%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(31, 'String 2 - Tone B', 0, '43.6%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(32, 'String 2 - Inharmonicity B', 0, '28.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(33, 'String 2 - Decay B', 0, '89.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(34, 'String 2 - Coupling', 0, '19.8%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(35, 'String 2 - Balance', 0, '24.9%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(36, 'String 2 - Volume', 0, '-5.8dB ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(37, 'String 3 - Tone A', 0, '69.4%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(38, 'String 3 - Inharmonicity A', 0, '34.4%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(39, 'String 3 - Decay A', 0, '53.7%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(40, 'String 3 - Tone B', 0, '36.2%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(41, 'String 3 - Inharmonicity B', 0, '38.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(42, 'String 3 - Decay B', 0, '89.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(43, 'String 3 - Coupling', 0, '19.8%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(44, 'String 3 - Balance', 0, '24.9%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(45, 'String 3 - Volume', 0, '-4.3dB ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(46, 'String 4 - Tone A', 0, '54.4%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(47, 'String 4 - Inharmonicity A', 0, '45.6%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(48, 'String 4 - Decay A', 0, '53.7%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(49, 'String 4 - Tone B', 0, '28.7%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(50, 'String 4 - Inharmonicity B', 0, '48.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(51, 'String 4 - Decay B', 0, '89.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(52, 'String 4 - Coupling', 0, '19.8%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(53, 'String 4 - Balance', 0, '24.9%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(54, 'String 4 - Volume', 0, '-2.9dB ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(55, 'String 5 - Tone A', 0, '39.4%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(56, 'String 5 - Inharmonicity A', 0, '56.8%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(57, 'String 5 - Decay A', 0, '53.7%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(58, 'String 5 - Tone B', 0, '21.3%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(59, 'String 5 - Inharmonicity B', 0, '58.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(60, 'String 5 - Decay B', 0, '89.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(61, 'String 5 - Coupling', 0, '19.8%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(62, 'String 5 - Balance', 0, '24.9%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(63, 'String 5 - Volume', 0, '-1.4dB ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(64, 'String 6 - Tone A', 0, '24.4%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(65, 'String 6 - Inharmonicity A', 0, '68.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(66, 'String 6 - Decay A', 0, '53.7%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(67, 'String 6 - Tone B', 0, '13.8%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(68, 'String 6 - Inharmonicity B', 0, '68.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(69, 'String 6 - Decay B', 0, '89.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(70, 'String 6 - Coupling', 0, '19.8%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(71, 'String 6 - Balance', 0, '24.9%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(72, 'String 6 - Volume', 0, '0.0dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(73, 'Hammer-On - Amp', 0, '85.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(74, 'Hammer-On - Tone', 0, '71.7%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(75, 'Mute - Harmonics Decay', 0, '40.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(76, 'Mute - Harmonics Tone', 0, '50.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(77, 'Mute - Contact', 0, '40.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(78, 'Mute - Time', 0, '47.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(79, 'Palm Mute - Tone', 0, '47.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(80, 'Palm Mute - Decay', 0, '84.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(81, 'Body - Size', 0, 'Medium ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(82, 'Body - Low Cut', 0, '125Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(83, 'Body - Air Cavity Decay', 0, '40.6%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(84, 'Body - Plate Decay', 0, '29.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(85, 'Body - Plate Tone', 0, '50.1%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(86, 'Equalizer - Low Freq', 0, '159Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(87, 'Equalizer - Low Gain', 0, '8.1dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(88, 'Equalizer - Low Mid Freq', 0, '241Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(89, 'Equalizer - Low Mid Gain', 0, '3.3dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(90, 'Equalizer - Low Mid Q', 0, '1.03鐛ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(91, 'Equalizer - High Mid Freq', 0, '968Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(92, 'Equalizer - High Mid Gain', 0, '-5.7dB ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(93, 'Equalizer - High Mid Q', 0, '0.37鐛ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(94, 'Equalizer - High Freq', 0, '2.52kHz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(95, 'Equalizer - High Gain', 0, '1.8dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(96, 'Equalizer - Side Chain', 0, 'Normal ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(97, 'Equalizer - On', 0, 'On ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(98, 'Compressor - Threshold', 0, '-17.4dB ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(99, 'Compressor - Ratio', 0, '1.50鐛ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(100, 'Compressor - Attack', 0, '15.0ms ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(101, 'Compressor - Release', 0, '150msˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(102, 'Compressor - Gain', 0, '4.9dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(103, 'Compressor - Pre', 0, 'Off ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(104, 'Compressor - On', 0, 'On ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(105, 'Effect 1 - On', 0, 'Off ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(106, 'Effect 1 - Type', 0, 'Distort ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(107, 'Delay 1 - Wet', 0, '-15.5dB ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(108, 'Delay 1 - Dry', 0, '0.0dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(109, 'Delay 1 - Sync On', 0, 'Off ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(110, 'Delay 1 - Sync Rate', 0, '1/16 3 ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(111, 'Delay 1 - Delay', 0, '0.13sˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(112, 'Delay 1 - Feedback', 0, '-15.4dB ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(113, 'Delay 1 - Cutoff', 0, '13.1kHz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(114, 'Delay 1 - Pan', 0, '-26.0% ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(115, 'Distortion 1 - Drive', 0, '8.9dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(116, 'Distortion 1 - Volume', 0, '-5.8dB ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(117, 'Distortion 1 - Shape', 0, 'Warm Tu ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(118, 'Distortion 1 - Tone', 0, '63.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(119, 'Distortion 1 - Mix', 0, '100.0% ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(120, 'Phaser 1 - Mix', 0, '50.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(121, 'Phaser 1 - Depth', 0, '50.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(122, 'Phaser 1 - Frequency', 0, '120Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(123, 'Phaser 1 - Feedback', 0, '-8.6dB ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(124, 'Phaser 1 - Sync On', 0, 'Off ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(125, 'Phaser 1 - Sync Rate', 0, '1/8 ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(126, 'Phaser 1 - Rate', 0, '1.2Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(127, 'Vintage Chorus 1 - Depth', 0, '44.9%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(128, 'Vintage Chorus 1 - Spread', 0, '65.4%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(129, 'Vintage Chorus 1 - Delay', 0, '3ms ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(130, 'Vintage Chorus 1 - Feedback', 0, '-35.9dB ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(131, 'Vintage Chorus 1 - Sync On', 0, 'Off ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(132, 'Vintage Chorus 1 - Sync Rate', 0, '1/8 ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(133, 'Vintage Chorus 1 - Rate', 0, '0.9Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(134, 'Vintage Chorus 1 - Mix', 0, '77.2%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(135, 'Vintage Chorus 1 - Mode', 0, 'Chorus ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(136, 'Chorus 1 - Depth', 0, '50.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(137, 'Chorus 1 - Fat', 0, '2搒 ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(138, 'Chorus 1 - Spread', 0, '62.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(139, 'Chorus 1 - Sync On', 0, 'Off ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(140, 'Chorus 1 - Sync Rate', 0, '1/4 ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(141, 'Chorus 1 - Rate', 0, '0.5Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(142, 'Chorus 1 - Mix', 0, '50.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(143, 'Flanger 1 - Depth', 0, '78.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(144, 'Flanger 1 - Delay', 0, '30.0ms ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(145, 'Flanger 1 - Feedback', 0, '-6.0dB ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(146, 'Flanger 1 - Sync On', 0, 'Off ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(147, 'Flanger 1 - Sync Rate', 0, '1/4 ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(148, 'Flanger 1 - Rate', 0, '0.4Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(149, 'Flanger 1 - Mix', 0, '50.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(150, 'Tremolo 1 - Depth', 0, '25.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(151, 'Tremolo 1 - Sync On', 0, 'Off ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(152, 'Tremolo 1 - Sync Rate', 0, '1/32鐛ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(153, 'Tremolo 1 - Rate', 0, '1.0Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(154, 'Tremolo 1 - Stereo', 0, 'Stereo ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(155, 'Tremolo 1 - Shape', 0, '50.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(156, 'Auto Wah 1 - Depth', 0, '43.1%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(157, 'Auto Wah 1 - Freq', 0, '400Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(158, 'Auto Wah 1 - Speed', 0, '69.9%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(159, 'Wah Wah 1 - Depth', 0, '88.8%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(160, 'Wah Wah 1 - Freq', 0, '557Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(161, 'Wah Wah 1 - Sync On', 0, 'Off ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(162, 'Wah Wah 1 - Sync Rate', 0, '1/8 ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(163, 'Wah Wah 1 - Rate', 0, '1.7Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(164, 'Notch 1 - Depth', 0, '88.8%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(165, 'Notch 1 - Freq', 0, '557Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(166, 'Notch 1 - Sync On', 0, 'Off ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(167, 'Notch 1 - Sync Rate', 0, '1/8 ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(168, 'Notch 1 - Rate', 0, '1.0Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(169, 'Effect 2 - On', 0, 'Off ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(170, 'Effect 2 - Type', 0, 'Tremolo ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(171, 'Delay 2 - Wet', 0, '-15.5dB ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(172, 'Delay 2 - Dry', 0, '0.0dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(173, 'Delay 2 - Sync On', 0, 'Off ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(174, 'Delay 2 - Sync Rate', 0, '1/16 3 ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(175, 'Delay 2 - Delay', 0, '0.14sˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(176, 'Delay 2 - Feedback', 0, '-12.0dB ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(177, 'Delay 2 - Cutoff', 0, '5.42kHz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(178, 'Delay 2 - Pan', 0, '-26.0% ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(179, 'Distortion 2 - Drive', 0, '1.2dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(180, 'Distortion 2 - Volume', 0, '-1.2dB ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(181, 'Distortion 2 - Shape', 0, 'Warm Tu ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(182, 'Distortion 2 - Tone', 0, '50.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(183, 'Distortion 2 - Mix', 0, '100.0% ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(184, 'Phaser 2 - Mix', 0, '50.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(185, 'Phaser 2 - Depth', 0, '42.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(186, 'Phaser 2 - Frequency', 0, '233Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(187, 'Phaser 2 - Feedback', 0, '-6.6dB ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(188, 'Phaser 2 - Sync On', 0, 'Off ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(189, 'Phaser 2 - Sync Rate', 0, '1/4 ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(190, 'Phaser 2 - Rate', 0, '0.4Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(191, 'Vintage Chorus 2 - Depth', 0, '25.9%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(192, 'Vintage Chorus 2 - Spread', 0, '0.0%鐛ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(193, 'Vintage Chorus 2 - Delay', 0, '40ms鐛ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(194, 'Vintage Chorus 2 - Feedback', 0, '-40.0dB ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(195, 'Vintage Chorus 2 - Sync On', 0, 'Off ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(196, 'Vintage Chorus 2 - Sync Rate', 0, '1/4 ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(197, 'Vintage Chorus 2 - Rate', 0, '1.0Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(198, 'Vintage Chorus 2 - Mix', 0, '17.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(199, 'Vintage Chorus 2 - Mode', 0, 'Chorus ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(200, 'Chorus 2 - Depth', 0, '50.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(201, 'Chorus 2 - Fat', 0, '4搒 ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(202, 'Chorus 2 - Spread', 0, '62.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(203, 'Chorus 2 - Sync On', 0, 'Off ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(204, 'Chorus 2 - Sync Rate', 0, '1/4 ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(205, 'Chorus 2 - Rate', 0, '0.5Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(206, 'Chorus 2 - Mix', 0, '20.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(207, 'Flanger 2 - Depth', 0, '78.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(208, 'Flanger 2 - Delay', 0, '30.0ms ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(209, 'Flanger 2 - Feedback', 0, '-6.0dB ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(210, 'Flanger 2 - Sync On', 0, 'Off ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(211, 'Flanger 2 - Sync Rate', 0, '1/4 ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(212, 'Flanger 2 - Rate', 0, '0.4Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(213, 'Flanger 2 - Mix', 0, '50.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(214, 'Tremolo 2 - Depth', 0, '50.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(215, 'Tremolo 2 - Sync On', 0, 'Off ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(216, 'Tremolo 2 - Sync Rate', 0, '1/4 ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(217, 'Tremolo 2 - Rate', 0, '3.0Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(218, 'Tremolo 2 - Stereo', 0, 'Mono鐛ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(219, 'Tremolo 2 - Shape', 0, '0.0%鐛ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(220, 'Auto Wah 2 - Depth', 0, '42.1%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(221, 'Auto Wah 2 - Freq', 0, '432Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(222, 'Auto Wah 2 - Speed', 0, '71.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(223, 'Wah Wah 2 - Depth', 0, '53.9%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(224, 'Wah Wah 2 - Freq', 0, '707Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(225, 'Wah Wah 2 - Sync On', 0, 'Off ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(226, 'Wah Wah 2 - Sync Rate', 0, '1/4 ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(227, 'Wah Wah 2 - Rate', 0, '1.7Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(228, 'Notch 2 - Depth', 0, '50.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(229, 'Notch 2 - Freq', 0, '620Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(230, 'Notch 2 - Sync On', 0, 'Off ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(231, 'Notch 2 - Sync Rate', 0, '1/4 ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(232, 'Notch 2 - Rate', 0, '1.5Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(233, 'Reverb - Size', 0, 'Studio ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(234, 'Reverb - Decay', 0, '2.00鐛ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(235, 'Reverb - Diffusion', 0, '75.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(236, 'Reverb - Low Damp', 0, '103Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(237, 'Reverb - High Damp', 0, '0.25鐛ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(238, 'Reverb - Mix', 0, '24.7%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(239, 'Reverb - On', 0, 'On ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(240, 'Global - Volume', 0, '-3.2dB ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(241, 'Pickups - Selector', 0, 'Neck鐛ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(242, 'Pickups - Volume', 0, '0.0dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(243, 'Pickups - Neck Position', 0, '23.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(244, 'Pickups - Neck Frequency', 0, '5.00kHz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(245, 'Pickups - Neck Resonance', 0, '0.90鐛ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(246, 'Pickups - Bridge Position', 0, '6.3%鐛ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(247, 'Pickups - Bridge Frequency', 0, '5.00kHz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(248, 'Pickups - Bridge Resonance', 0, '0.90鐛ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(249, 'Pickups - Bridge Trim', 0, '0.0dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(250, 'Pickups - Type', 0, 'Single ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(251, 'Amplifier - Channel', 0, 'Channel ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(252, 'Amplifier - Bite', 0, 'Off ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(253, 'Amplifier - Channel 1 Drive', 0, '10.0dB ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(254, 'Amplifier - Channel 1 Mid', 0, '0.0dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(255, 'Amplifier - Channel 1 Level', 0, '-7.0dB ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(256, 'Amplifier - Channel 2 Drive', 0, '20.0dB ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(257, 'Amplifier - Channel 2 Mid', 0, '0.0dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(258, 'Amplifier - Channel 2 Level', 0, '-17.0dB ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(259, 'Amplifier - Eq Low', 0, '0.0dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(260, 'Amplifier - Eq High', 0, '0.0dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(261, 'Amplifier - Amplifier On', 0, 'On ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(262, 'Amplifier - Spring Reverb Mix', 0, '20.0%ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(263, 'Amplifier - Spring Reverb On', 0, 'Off ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(264, 'Amplifier - Cabinet Open', 0, 'Closed ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(265, 'Amplifier - Cabinet On', 0, 'On ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(266, 'Palm Mute - Tone Velocity', 0, '0.00鐛ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(267, 'Equalizer 1 - Low Freq', 0, '100Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(268, 'Equalizer 1 - Low Gain', 0, '0.0dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(269, 'Equalizer 1 - Low Mid Freq', 0, '800Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(270, 'Equalizer 1 - Low Mid Gain', 0, '0.0dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(271, 'Equalizer 1 - Low Mid Q', 0, '0.71鐛ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(272, 'Equalizer 1 - High Mid Freq', 0, '1.60kHz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(273, 'Equalizer 1 - High Mid Gain', 0, '0.0dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(274, 'Equalizer 1 - High Mid Q', 0, '0.71鐛ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(275, 'Equalizer 1 - High Freq', 0, '4.00kHz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(276, 'Equalizer 1 - High Gain', 0, '0.0dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(277, 'Equalizer 1 - Output', 0, '0.0dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(278, 'Compressor 1 - Threshold', 0, '0.0dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(279, 'Compressor 1 - Ratio', 0, '4.00鐛ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(280, 'Compressor 1 - Attack', 0, '1.0msˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(281, 'Compressor 1 - Release', 0, '100msˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(282, 'Compressor 1 - Makeup', 0, '0.0dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(283, 'Compressor 1 - Mix', 0, 'W100 D0 ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(284, 'Equalizer 2 - Low Freq', 0, '100Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(285, 'Equalizer 2 - Low Gain', 0, '0.0dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(286, 'Equalizer 2 - Low Mid Freq', 0, '800Hz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(287, 'Equalizer 2 - Low Mid Gain', 0, '0.0dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(288, 'Equalizer 2 - Low Mid Q', 0, '0.71鐛ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(289, 'Equalizer 2 - High Mid Freq', 0, '1.60kHz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(290, 'Equalizer 2 - High Mid Gain', 0, '0.0dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(291, 'Equalizer 2 - High Mid Q', 0, '0.71鐛ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(292, 'Equalizer 2 - High Freq', 0, '4.00kHz ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(293, 'Equalizer 2 - High Gain', 0, '0.0dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(294, 'Equalizer 2 - Output', 0, '0.0dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(295, 'Compressor 2 - Threshold', 0, '0.0dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(296, 'Compressor 2 - Ratio', 0, '4.00鐛ˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(297, 'Compressor 2 - Attack', 0, '1.0msˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(298, 'Compressor 2 - Release', 0, '100msˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(299, 'Compressor 2 - Makeup', 0, '0.0dBˀ ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(300, 'Compressor 2 - Mix', 0, 'W100 D0 ', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4096, 'MIDI CC #0 (Bank select MSB)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4097, 'MIDI CC #1 (Modulation wheel)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4098, 'MIDI CC #2 (Breath controller)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4099, 'MIDI CC #3', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4100, 'MIDI CC #4 (Foot controller)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4101, 'MIDI CC #5 (Portamento time)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4102, 'MIDI CC #6 (Data entry MSB)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4103, 'MIDI CC #7 (Main volume)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4104, 'MIDI CC #8 (Balance)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4105, 'MIDI CC #9', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4106, 'MIDI CC #10 (Pan)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4107, 'MIDI CC #11 (Expression controller)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4108, 'MIDI CC #12 (Control 1)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4109, 'MIDI CC #13 (Control 2)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4110, 'MIDI CC #14', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4111, 'MIDI CC #15', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4112, 'MIDI CC #16 (General purpose controller 1)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4113, 'MIDI CC #17 (General purpose controller 2)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4114, 'MIDI CC #18 (General purpose controller 3)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4115, 'MIDI CC #19 (General purpose controller 4)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4116, 'MIDI CC #20', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4117, 'MIDI CC #21', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4118, 'MIDI CC #22', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4119, 'MIDI CC #23', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4120, 'MIDI CC #24', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4121, 'MIDI CC #25', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4122, 'MIDI CC #26', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4123, 'MIDI CC #27', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4124, 'MIDI CC #28', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4125, 'MIDI CC #29', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4126, 'MIDI CC #30', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4127, 'MIDI CC #31', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4128, 'MIDI CC #32 (Bank select LSB)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4129, 'MIDI CC #33 (Modulation wheel LSB)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4130, 'MIDI CC #34 (Breath controller LSB)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4131, 'MIDI CC #35', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4132, 'MIDI CC #36 (Foot controller LSB)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4133, 'MIDI CC #37 (Portamento time LSB)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4134, 'MIDI CC #38 (Data entry LSB )', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4135, 'MIDI CC #39 (Main volume LSB)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4136, 'MIDI CC #40 (Balance LSB)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4137, 'MIDI CC #41', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4138, 'MIDI CC #42 (Pan LSB)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4139, 'MIDI CC #43 (Expression controller LSB)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4140, 'MIDI CC #44 (Control 1 LSB)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4141, 'MIDI CC #45 (Control 2 LSB)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4142, 'MIDI CC #46', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4143, 'MIDI CC #47', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4144, 'MIDI CC #48 (General purpose controller 1 LSB)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4145, 'MIDI CC #49 (General purpose controller 2 LSB)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4146, 'MIDI CC #50 (General purpose controller 3 LSB)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4147, 'MIDI CC #51 (General purpose controller 4 LSB)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4148, 'MIDI CC #52', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4149, 'MIDI CC #53', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4150, 'MIDI CC #54', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4151, 'MIDI CC #55', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4152, 'MIDI CC #56', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4153, 'MIDI CC #57', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4154, 'MIDI CC #58', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4155, 'MIDI CC #59', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4156, 'MIDI CC #60', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4157, 'MIDI CC #61', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4158, 'MIDI CC #62', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4159, 'MIDI CC #63', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4160, 'MIDI CC #64 (Damper pedal (sustain))', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4161, 'MIDI CC #65 (Portamento)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4162, 'MIDI CC #66 (Sostenuto)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4163, 'MIDI CC #67 (Soft pedal)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4164, 'MIDI CC #68 (Legato footswitch)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4165, 'MIDI CC #69 (Hold 2)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4166, 'MIDI CC #70 (Sound variation)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4167, 'MIDI CC #71 (Harmonic content)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4168, 'MIDI CC #72 (Release time)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4169, 'MIDI CC #73 (Attack time)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4170, 'MIDI CC #74 (Brightness)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4171, 'MIDI CC #75 (Sound controller 6)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4172, 'MIDI CC #76 (Sound controller 7)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4173, 'MIDI CC #77 (Sound controller 8)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4174, 'MIDI CC #78 (Sound controller 9)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4175, 'MIDI CC #79 (Sound controller 10)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4176, 'MIDI CC #80 (General purpose controller 5)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4177, 'MIDI CC #81 (General purpose controller 6)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4178, 'MIDI CC #82 (General purpose controller 7)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4179, 'MIDI CC #83 (General purpose controller 8)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4180, 'MIDI CC #84 (Portamento control)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4181, 'MIDI CC #85', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4182, 'MIDI CC #86', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4183, 'MIDI CC #87', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4184, 'MIDI CC #88', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4185, 'MIDI CC #89', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4186, 'MIDI CC #90', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4187, 'MIDI CC #91 (Reverb depth)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4188, 'MIDI CC #92 (Tremolo depth)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4189, 'MIDI CC #93 (Chorus depth)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4190, 'MIDI CC #94 (Celeste depth)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4191, 'MIDI CC #95 (Phaser depth)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4192, 'MIDI CC #96 (Data increment)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4193, 'MIDI CC #97 (Data decrement)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4194, 'MIDI CC #98 (NRPN LSB)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4195, 'MIDI CC #99 (NRPN MSB)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4196, 'MIDI CC #100 (RPN LSB)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4197, 'MIDI CC #101 (RPN MSB)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4198, 'MIDI CC #102', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4199, 'MIDI CC #103', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4200, 'MIDI CC #104', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4201, 'MIDI CC #105', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4202, 'MIDI CC #106', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4203, 'MIDI CC #107', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4204, 'MIDI CC #108', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4205, 'MIDI CC #109', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4206, 'MIDI CC #110', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4207, 'MIDI CC #111', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4208, 'MIDI CC #112', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4209, 'MIDI CC #113', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4210, 'MIDI CC #114', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4211, 'MIDI CC #115', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4212, 'MIDI CC #116', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4213, 'MIDI CC #117', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4214, 'MIDI CC #118', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4215, 'MIDI CC #119', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4216, 'MIDI CC #120 (All sound off)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4217, 'MIDI CC #121 (Reset all controllers)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4218, 'MIDI CC #122 (Local control on/off)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4219, 'MIDI CC #123 (All notes off)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4220, 'MIDI CC #124 (Omni mode off)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4221, 'MIDI CC #125 (Omni mode on)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4222, 'MIDI CC #126 (Mono mode on)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4223, 'MIDI CC #127 (Poly mode on)', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4224, 'MIDI Channel 1 Aftertouch', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4225, 'MIDI Channel 2 Aftertouch', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4226, 'MIDI Channel 3 Aftertouch', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4227, 'MIDI Channel 4 Aftertouch', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4228, 'MIDI Channel 5 Aftertouch', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4229, 'MIDI Channel 6 Aftertouch', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4230, 'MIDI Channel 7 Aftertouch', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4231, 'MIDI Channel 8 Aftertouch', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4232, 'MIDI Channel 9 Aftertouch', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4233, 'MIDI Channel 10 Aftertouch', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4234, 'MIDI Channel 11 Aftertouch', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4235, 'MIDI Channel 12 Aftertouch', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4236, 'MIDI Channel 13 Aftertouch', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4237, 'MIDI Channel 14 Aftertouch', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4238, 'MIDI Channel 15 Aftertouch', 0, '', False) )
plStrumGS2.addParamToGroup('ALL', TnfxParameter(4239, 'MIDI Channel 16 Aftertouch', 0, '', False) )

# set up the predetermined USER1 and USER2 knob parameters to link to the 8 macros
plStrumGS2.assignParameterToUserKnob(KM_USER1, 0, TnfxParameter(0, 'Play Mode',   0, 'Guitar',  False, 2) )
plStrumGS2.assignParameterToUserKnob(KM_USER1, 1, TnfxParameter(4, 'Auto Strum',  0, 'Off',     False, 1) )
plStrumGS2.assignParameterToUserKnob(KM_USER1, 2, TnfxParameter(7, 'Chord Type',  0, 'Movable', False) )
plStrumGS2.assignParameterToUserKnob(KM_USER1, 3, TnfxParameter(8, 'Voicing Pos', 0, 'Fret 1',  False) )
# -----------------------------------------------------------------
