#   PluginName:  Slicex
#   ParamCount:  352
# -----------------------------------------------------------------
from fireNFX_Classes import TnfxParameter, TnfxChannelPlugin
plSlicex = TnfxChannelPlugin('Slicex')
plSlicex.addParamToGroup('MAIN', TnfxParameter(0, 'Play/pause', 0, '', False) )
plSlicex.addParamToGroup('MAIN', TnfxParameter(1, 'Live selection', 0, '', False) )
plSlicex.addParamToGroup('MAIN', TnfxParameter(2, 'Master level', 0, '0.0dB  1.00', False) )
plSlicex.addParamToGroup('MAIN', TnfxParameter(3, 'Master randomness level', 0, '100%', False) )
plSlicex.addParamToGroup('MAIN', TnfxParameter(4, 'Master LFO level', 0, '100%', False) )
plSlicex.addParamToGroup('MAIN', TnfxParameter(5, 'Master pitch', 0, '+0.00 cent', False) )
plSlicex.addParamToGroup('MAIN', TnfxParameter(6, 'Modulation X', 0, '50%', False) )
plSlicex.addParamToGroup('MAIN', TnfxParameter(7, 'Modulation Y', 0, '50%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(8, '#1-Filt cut env/LFO amt', 0, '50%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(9, '#1-FiltCutFreq', 0, '50%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(10, '#1-FiltRes', 0, '50%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(11, '#1-Pan-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(12, '#1-Pan-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(13, '#1-Pan-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(14, '#1-Pan-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(15, '#1-Pan-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(16, '#1-Pan-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(17, '#1-Pan-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(18, '#1-Pan-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(19, '#1-Vol-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(20, '#1-Vol-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(21, '#1-Vol-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(22, '#1-Vol-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(23, '#1-Vol-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(24, '#1-Vol-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(25, '#1-Vol-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(26, '#1-Vol-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(27, '#1-FiltCutFreq-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(28, '#1-FiltCutFreq-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(29, '#1-FiltCutFreq-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(30, '#1-FiltCutFreq-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(31, '#1-FiltCutFreq-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(32, '#1-FiltCutFreq-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(33, '#1-FiltCutFreq-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(34, '#1-FiltCutFreq-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(35, '#1-FiltRes-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(36, '#1-FiltRes-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(37, '#1-FiltRes-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(38, '#1-FiltRes-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(39, '#1-FiltRes-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(40, '#1-FiltRes-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(41, '#1-FiltRes-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(42, '#1-FiltRes-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(43, '#1-Spd-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(44, '#1-Spd-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(45, '#1-Spd-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(46, '#1-Spd-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(47, '#1-Spd-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(48, '#1-Spd-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(49, '#1-Spd-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #1', TnfxParameter(50, '#1-Spd-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(51, '#2-Filt cut env/LFO amt', 0, '50%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(52, '#2-FiltCutFreq', 0, '50%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(53, '#2-FiltRes', 0, '50%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(54, '#2-Pan-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(55, '#2-Pan-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(56, '#2-Pan-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(57, '#2-Pan-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(58, '#2-Pan-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(59, '#2-Pan-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(60, '#2-Pan-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(61, '#2-Pan-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(62, '#2-Vol-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(63, '#2-Vol-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(64, '#2-Vol-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(65, '#2-Vol-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(66, '#2-Vol-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(67, '#2-Vol-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(68, '#2-Vol-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(69, '#2-Vol-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(70, '#2-FiltCutFreq-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(71, '#2-FiltCutFreq-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(72, '#2-FiltCutFreq-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(73, '#2-FiltCutFreq-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(74, '#2-FiltCutFreq-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(75, '#2-FiltCutFreq-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(76, '#2-FiltCutFreq-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(77, '#2-FiltCutFreq-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(78, '#2-FiltRes-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(79, '#2-FiltRes-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(80, '#2-FiltRes-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(81, '#2-FiltRes-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(82, '#2-FiltRes-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(83, '#2-FiltRes-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(84, '#2-FiltRes-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(85, '#2-FiltRes-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(86, '#2-Spd-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(87, '#2-Spd-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(88, '#2-Spd-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(89, '#2-Spd-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(90, '#2-Spd-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(91, '#2-Spd-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(92, '#2-Spd-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #2', TnfxParameter(93, '#2-Spd-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(94, '#3-Filt cut env/LFO amt', 0, '50%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(95, '#3-FiltCutFreq', 0, '50%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(96, '#3-FiltRes', 0, '50%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(97, '#3-Pan-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(98, '#3-Pan-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(99, '#3-Pan-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(100, '#3-Pan-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(101, '#3-Pan-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(102, '#3-Pan-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(103, '#3-Pan-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(104, '#3-Pan-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(105, '#3-Vol-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(106, '#3-Vol-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(107, '#3-Vol-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(108, '#3-Vol-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(109, '#3-Vol-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(110, '#3-Vol-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(111, '#3-Vol-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(112, '#3-Vol-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(113, '#3-FiltCutFreq-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(114, '#3-FiltCutFreq-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(115, '#3-FiltCutFreq-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(116, '#3-FiltCutFreq-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(117, '#3-FiltCutFreq-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(118, '#3-FiltCutFreq-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(119, '#3-FiltCutFreq-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(120, '#3-FiltCutFreq-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(121, '#3-FiltRes-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(122, '#3-FiltRes-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(123, '#3-FiltRes-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(124, '#3-FiltRes-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(125, '#3-FiltRes-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(126, '#3-FiltRes-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(127, '#3-FiltRes-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(128, '#3-FiltRes-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(129, '#3-Spd-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(130, '#3-Spd-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(131, '#3-Spd-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(132, '#3-Spd-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(133, '#3-Spd-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(134, '#3-Spd-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(135, '#3-Spd-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #3', TnfxParameter(136, '#3-Spd-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(137, '#4-Filt cut env/LFO amt', 0, '50%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(138, '#4-FiltCutFreq', 0, '50%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(139, '#4-FiltRes', 0, '50%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(140, '#4-Pan-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(141, '#4-Pan-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(142, '#4-Pan-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(143, '#4-Pan-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(144, '#4-Pan-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(145, '#4-Pan-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(146, '#4-Pan-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(147, '#4-Pan-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(148, '#4-Vol-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(149, '#4-Vol-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(150, '#4-Vol-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(151, '#4-Vol-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(152, '#4-Vol-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(153, '#4-Vol-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(154, '#4-Vol-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(155, '#4-Vol-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(156, '#4-FiltCutFreq-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(157, '#4-FiltCutFreq-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(158, '#4-FiltCutFreq-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(159, '#4-FiltCutFreq-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(160, '#4-FiltCutFreq-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(161, '#4-FiltCutFreq-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(162, '#4-FiltCutFreq-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(163, '#4-FiltCutFreq-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(164, '#4-FiltRes-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(165, '#4-FiltRes-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(166, '#4-FiltRes-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(167, '#4-FiltRes-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(168, '#4-FiltRes-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(169, '#4-FiltRes-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(170, '#4-FiltRes-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(171, '#4-FiltRes-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(172, '#4-Spd-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(173, '#4-Spd-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(174, '#4-Spd-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(175, '#4-Spd-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(176, '#4-Spd-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(177, '#4-Spd-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(178, '#4-Spd-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #4', TnfxParameter(179, '#4-Spd-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(180, '#5-Filt cut env/LFO amt', 0, '50%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(181, '#5-FiltCutFreq', 0, '50%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(182, '#5-FiltRes', 0, '50%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(183, '#5-Pan-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(184, '#5-Pan-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(185, '#5-Pan-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(186, '#5-Pan-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(187, '#5-Pan-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(188, '#5-Pan-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(189, '#5-Pan-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(190, '#5-Pan-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(191, '#5-Vol-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(192, '#5-Vol-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(193, '#5-Vol-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(194, '#5-Vol-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(195, '#5-Vol-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(196, '#5-Vol-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(197, '#5-Vol-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(198, '#5-Vol-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(199, '#5-FiltCutFreq-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(200, '#5-FiltCutFreq-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(201, '#5-FiltCutFreq-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(202, '#5-FiltCutFreq-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(203, '#5-FiltCutFreq-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(204, '#5-FiltCutFreq-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(205, '#5-FiltCutFreq-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(206, '#5-FiltCutFreq-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(207, '#5-FiltRes-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(208, '#5-FiltRes-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(209, '#5-FiltRes-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(210, '#5-FiltRes-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(211, '#5-FiltRes-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(212, '#5-FiltRes-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(213, '#5-FiltRes-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(214, '#5-FiltRes-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(215, '#5-Spd-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(216, '#5-Spd-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(217, '#5-Spd-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(218, '#5-Spd-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(219, '#5-Spd-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(220, '#5-Spd-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(221, '#5-Spd-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #5', TnfxParameter(222, '#5-Spd-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(223, '#6-Filt cut env/LFO amt', 0, '50%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(224, '#6-FiltCutFreq', 0, '50%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(225, '#6-FiltRes', 0, '50%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(226, '#6-Pan-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(227, '#6-Pan-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(228, '#6-Pan-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(229, '#6-Pan-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(230, '#6-Pan-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(231, '#6-Pan-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(232, '#6-Pan-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(233, '#6-Pan-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(234, '#6-Vol-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(235, '#6-Vol-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(236, '#6-Vol-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(237, '#6-Vol-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(238, '#6-Vol-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(239, '#6-Vol-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(240, '#6-Vol-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(241, '#6-Vol-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(242, '#6-FiltCutFreq-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(243, '#6-FiltCutFreq-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(244, '#6-FiltCutFreq-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(245, '#6-FiltCutFreq-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(246, '#6-FiltCutFreq-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(247, '#6-FiltCutFreq-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(248, '#6-FiltCutFreq-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(249, '#6-FiltCutFreq-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(250, '#6-FiltRes-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(251, '#6-FiltRes-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(252, '#6-FiltRes-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(253, '#6-FiltRes-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(254, '#6-FiltRes-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(255, '#6-FiltRes-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(256, '#6-FiltRes-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(257, '#6-FiltRes-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(258, '#6-Spd-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(259, '#6-Spd-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(260, '#6-Spd-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(261, '#6-Spd-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(262, '#6-Spd-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(263, '#6-Spd-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(264, '#6-Spd-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #6', TnfxParameter(265, '#6-Spd-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(266, '#7-Filt cut env/LFO amt', 0, '50%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(267, '#7-FiltCutFreq', 0, '50%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(268, '#7-FiltRes', 0, '50%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(269, '#7-Pan-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(270, '#7-Pan-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(271, '#7-Pan-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(272, '#7-Pan-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(273, '#7-Pan-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(274, '#7-Pan-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(275, '#7-Pan-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(276, '#7-Pan-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(277, '#7-Vol-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(278, '#7-Vol-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(279, '#7-Vol-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(280, '#7-Vol-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(281, '#7-Vol-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(282, '#7-Vol-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(283, '#7-Vol-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(284, '#7-Vol-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(285, '#7-FiltCutFreq-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(286, '#7-FiltCutFreq-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(287, '#7-FiltCutFreq-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(288, '#7-FiltCutFreq-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(289, '#7-FiltCutFreq-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(290, '#7-FiltCutFreq-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(291, '#7-FiltCutFreq-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(292, '#7-FiltCutFreq-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(293, '#7-FiltRes-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(294, '#7-FiltRes-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(295, '#7-FiltRes-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(296, '#7-FiltRes-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(297, '#7-FiltRes-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(298, '#7-FiltRes-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(299, '#7-FiltRes-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(300, '#7-FiltRes-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(301, '#7-Spd-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(302, '#7-Spd-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(303, '#7-Spd-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(304, '#7-Spd-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(305, '#7-Spd-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(306, '#7-Spd-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(307, '#7-Spd-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #7', TnfxParameter(308, '#7-Spd-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(309, '#8-Filt cut env/LFO amt', 0, '50%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(310, '#8-FiltCutFreq', 0, '50%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(311, '#8-FiltRes', 0, '50%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(312, '#8-Pan-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(313, '#8-Pan-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(314, '#8-Pan-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(315, '#8-Pan-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(316, '#8-Pan-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(317, '#8-Pan-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(318, '#8-Pan-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(319, '#8-Pan-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(320, '#8-Vol-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(321, '#8-Vol-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(322, '#8-Vol-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(323, '#8-Vol-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(324, '#8-Vol-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(325, '#8-Vol-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(326, '#8-Vol-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(327, '#8-Vol-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(328, '#8-FiltCutFreq-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(329, '#8-FiltCutFreq-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(330, '#8-FiltCutFreq-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(331, '#8-FiltCutFreq-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(332, '#8-FiltCutFreq-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(333, '#8-FiltCutFreq-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(334, '#8-FiltCutFreq-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(335, '#8-FiltCutFreq-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(336, '#8-FiltRes-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(337, '#8-FiltRes-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(338, '#8-FiltRes-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(339, '#8-FiltRes-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(340, '#8-FiltRes-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(341, '#8-FiltRes-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(342, '#8-FiltRes-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(343, '#8-FiltRes-LFO pulse width', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(344, '#8-Spd-Attack', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(345, '#8-Spd-Decay', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(346, '#8-Spd-Sustain', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(347, '#8-Spd-Release', 0, '100%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(348, '#8-Spd-LFO speed (phase)', 0, '3:999', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(349, '#8-Spd-LFO tension', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(350, '#8-Spd-LFO skew', 0, '0%', False) )
plSlicex.addParamToGroup('GRP #8', TnfxParameter(351, '#8-Spd-LFO pulse width', 0, '0%', False) )
# -----------------------------------------------------------------
#    Non Blank Params Count: 704
