# Save this file as:  pluginFPC.py
# -----------------------------------------------------------------
#   PluginName:  FPC
#   ParamCount:  768
# -----------------------------------------------------------------
from fireNFX_Classes import TnfxParameter, TnfxChannelPlugin
from fireNFX_Defs import KM_USER1, KM_USER2
from fireNFX_PluginDefs import KNOWN_PLUGINS
plFPC = TnfxChannelPlugin('FPC')
plFPC.addParamToGroup('PAD-1', TnfxParameter(  0, 'volume', 0, '79%', False) )
plFPC.addParamToGroup('PAD-2', TnfxParameter(  1, 'volume', 0, '85%', False) )
plFPC.addParamToGroup('PAD-3', TnfxParameter(  2, 'volume', 0, '86%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(  3, 'Pad 4 volume', 0, '86%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(  4, 'Pad 5 volume', 0, '82%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(  5, 'Pad 6 volume', 0, '79%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(  6, 'Pad 7 volume', 0, '78%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(  7, 'Pad 8 volume', 0, '78%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(  8, 'Pad 9 volume', 0, '78%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(  9, 'Pad 10 volume', 0, '78%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 10, 'Pad 11 volume', 0, '75%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 11, 'Pad 12 volume', 0, '69%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 12, 'Pad 13 volume', 0, '80%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 13, 'Pad 14 volume', 0, '87%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 14, 'Pad 15 volume', 0, '78%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 15, 'Pad 16 volume', 0, '89%', False) )
plFPC.addParamToGroup('PAD-1', TnfxParameter( 16, 'pan', 0, '0%', False) )
plFPC.addParamToGroup('PAD-2', TnfxParameter( 17, 'pan', 0, '0%', False) )
plFPC.addParamToGroup('PAD-3', TnfxParameter( 18, 'pan', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 19, 'Pad 4 pan', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 20, 'Pad 5 pan', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 21, 'Pad 6 pan', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 22, 'Pad 7 pan', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 23, 'Pad 8 pan', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 24, 'Pad 9 pan', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 25, 'Pad 10 pan', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 26, 'Pad 11 pan', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 27, 'Pad 12 pan', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 28, 'Pad 13 pan', 0, '-26%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 29, 'Pad 14 pan', 0, '39%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 30, 'Pad 15 pan', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 31, 'Pad 16 pan', 0, '0%', False) )
plFPC.addParamToGroup('PAD-1', TnfxParameter( 32, 'mute', 0, 'off', False) )
plFPC.addParamToGroup('PAD-2', TnfxParameter( 33, 'mute', 0, 'off', False) )
plFPC.addParamToGroup('PAD-3', TnfxParameter( 34, 'mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 35, 'Pad 4 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 36, 'Pad 5 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 37, 'Pad 6 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 38, 'Pad 7 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 39, 'Pad 8 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 40, 'Pad 9 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 41, 'Pad 10 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 42, 'Pad 11 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 43, 'Pad 12 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 44, 'Pad 13 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 45, 'Pad 14 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 46, 'Pad 15 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 47, 'Pad 16 mute', 0, 'off', False) )
plFPC.addParamToGroup('PAD-1', TnfxParameter( 48, 'solo', 0, 'off', False) )
plFPC.addParamToGroup('PAD-2', TnfxParameter( 49, 'solo', 0, 'off', False) )
plFPC.addParamToGroup('PAD-3', TnfxParameter( 50, 'solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 51, 'Pad 4 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 52, 'Pad 5 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 53, 'Pad 6 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 54, 'Pad 7 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 55, 'Pad 8 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 56, 'Pad 9 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 57, 'Pad 10 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 58, 'Pad 11 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 59, 'Pad 12 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 60, 'Pad 13 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 61, 'Pad 14 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 62, 'Pad 15 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 63, 'Pad 16 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 64, 'Pad 17 volume', 0, '86%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 65, 'Pad 18 volume', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 66, 'Pad 19 volume', 0, '84%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 67, 'Pad 20 volume', 0, '83%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 68, 'Pad 21 volume', 0, '81%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 69, 'Pad 22 volume', 0, '80%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 70, 'Pad 23 volume', 0, '83%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 71, 'Pad 24 volume', 0, '79%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 72, 'Pad 25 volume', 0, '78%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 73, 'Pad 26 volume', 0, '78%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 74, 'Pad 27 volume', 0, '78%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 75, 'Pad 28 volume', 0, '78%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 76, 'Pad 29 volume', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 77, 'Pad 30 volume', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 78, 'Pad 31 volume', 0, '78%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 79, 'Pad 32 volume', 0, '78%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 80, 'Pad 17 pan', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 81, 'Pad 18 pan', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 82, 'Pad 19 pan', 0, '-30%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 83, 'Pad 20 pan', 0, '33%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 84, 'Pad 21 pan', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 85, 'Pad 22 pan', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 86, 'Pad 23 pan', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 87, 'Pad 24 pan', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 88, 'Pad 25 pan', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 89, 'Pad 26 pan', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 90, 'Pad 27 pan', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 91, 'Pad 28 pan', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 92, 'Pad 29 pan', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 93, 'Pad 30 pan', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 94, 'Pad 31 pan', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 95, 'Pad 32 pan', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 96, 'Pad 17 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 97, 'Pad 18 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 98, 'Pad 19 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter( 99, 'Pad 20 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(100, 'Pad 21 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(101, 'Pad 22 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(102, 'Pad 23 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(103, 'Pad 24 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(104, 'Pad 25 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(105, 'Pad 26 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(106, 'Pad 27 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(107, 'Pad 28 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(108, 'Pad 29 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(109, 'Pad 30 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(110, 'Pad 31 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(111, 'Pad 32 mute', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(112, 'Pad 17 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(113, 'Pad 18 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(114, 'Pad 19 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(115, 'Pad 20 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(116, 'Pad 21 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(117, 'Pad 22 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(118, 'Pad 23 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(119, 'Pad 24 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(120, 'Pad 25 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(121, 'Pad 26 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(122, 'Pad 27 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(123, 'Pad 28 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(124, 'Pad 29 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(125, 'Pad 30 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(126, 'Pad 31 solo', 0, 'off', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(127, 'Pad 32 solo', 0, 'off', False) )
plFPC.addParamToGroup('PAD-1', TnfxParameter(256, 'tune', 0, '37 cents', False) )
plFPC.addParamToGroup('PAD-2', TnfxParameter(257, 'tune', 0, '37 cents', False) )
plFPC.addParamToGroup('PAD-3', TnfxParameter(258, 'tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(259, 'Pad 4 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(260, 'Pad 5 tune', 0, '37 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(261, 'Pad 6 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(262, 'Pad 7 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(263, 'Pad 8 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(264, 'Pad 9 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(265, 'Pad 10 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(266, 'Pad 11 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(267, 'Pad 12 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(268, 'Pad 13 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(269, 'Pad 14 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(270, 'Pad 15 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(271, 'Pad 16 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(272, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(273, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(274, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(275, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(276, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(277, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(278, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(279, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(280, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(281, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(282, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(283, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(284, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(285, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(286, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(287, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(288, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(289, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(290, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(291, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(292, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(293, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(294, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(295, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(296, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(297, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(298, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(299, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(300, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(301, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(302, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(303, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(304, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(305, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(306, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(307, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(308, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(309, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(310, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(311, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(312, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(313, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(314, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(315, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(316, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(317, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(318, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(319, 'Pad 16 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(320, 'Pad 17 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(321, 'Pad 18 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(322, 'Pad 19 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(323, 'Pad 20 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(324, 'Pad 21 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(325, 'Pad 22 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(326, 'Pad 23 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(327, 'Pad 24 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(328, 'Pad 25 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(329, 'Pad 26 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(330, 'Pad 27 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(331, 'Pad 28 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(332, 'Pad 29 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(333, 'Pad 30 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(334, 'Pad 31 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(335, 'Pad 32 tune', 0, '0 cents', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(336, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(337, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(338, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(339, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(340, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(341, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(342, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(343, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(344, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(345, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(346, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(347, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(348, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(349, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(350, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(351, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(352, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(353, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(354, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(355, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(356, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(357, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(358, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(359, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(360, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(361, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(362, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(363, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(364, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(365, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(366, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(367, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(368, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(369, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(370, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(371, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(372, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(373, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(374, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(375, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(376, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(377, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(378, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(379, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(380, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(381, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(382, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(383, 'Pad 32 tune', 0, '', False) )
plFPC.addParamToGroup('PAD-1', TnfxParameter(512, 'volume attack', 0, '100%', False) )
plFPC.addParamToGroup('PAD-1', TnfxParameter(513, 'volume decay', 0, '100%', False) )
plFPC.addParamToGroup('PAD-1', TnfxParameter(514, 'volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('PAD-1', TnfxParameter(515, 'volume release', 0, '100%', False) )
plFPC.addParamToGroup('PAD-1', TnfxParameter(516, 'pan attack', 0, '100%', False) )
plFPC.addParamToGroup('PAD-1', TnfxParameter(517, 'pan decay', 0, '100%', False) )
plFPC.addParamToGroup('PAD-1', TnfxParameter(518, 'pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('PAD-1', TnfxParameter(519, 'pan release', 0, '100%', False) )
plFPC.addParamToGroup('PAD-2', TnfxParameter(520, 'volume attack', 0, '9%', False) )
plFPC.addParamToGroup('PAD-2', TnfxParameter(521, 'volume decay', 0, '59%', False) )
plFPC.addParamToGroup('PAD-2', TnfxParameter(522, 'volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('PAD-2', TnfxParameter(523, 'volume release', 0, '100%', False) )
plFPC.addParamToGroup('PAD-2', TnfxParameter(524, 'pan attack', 0, '100%', False) )
plFPC.addParamToGroup('PAD-2', TnfxParameter(525, 'pan decay', 0, '100%', False) )
plFPC.addParamToGroup('PAD-2', TnfxParameter(526, 'pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('PAD-2', TnfxParameter(527, 'pan release', 0, '100%', False) )
plFPC.addParamToGroup('PAD-3', TnfxParameter(528, 'volume attack', 0, '100%', False) )
plFPC.addParamToGroup('PAD-3', TnfxParameter(529, 'volume decay', 0, '100%', False) )
plFPC.addParamToGroup('PAD-3', TnfxParameter(530, 'volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('PAD-3', TnfxParameter(531, 'volume release', 0, '100%', False) )
plFPC.addParamToGroup('PAD-3', TnfxParameter(532, 'pan attack', 0, '100%', False) )
plFPC.addParamToGroup('PAD-3', TnfxParameter(533, 'pan decay', 0, '100%', False) )
plFPC.addParamToGroup('PAD-3', TnfxParameter(534, 'pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('PAD-3', TnfxParameter(535, 'pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(536, 'Pad 4 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(537, 'Pad 4 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(538, 'Pad 4 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(539, 'Pad 4 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(540, 'Pad 4 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(541, 'Pad 4 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(542, 'Pad 4 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(543, 'Pad 4 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(544, 'Pad 5 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(545, 'Pad 5 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(546, 'Pad 5 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(547, 'Pad 5 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(548, 'Pad 5 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(549, 'Pad 5 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(550, 'Pad 5 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(551, 'Pad 5 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(552, 'Pad 6 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(553, 'Pad 6 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(554, 'Pad 6 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(555, 'Pad 6 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(556, 'Pad 6 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(557, 'Pad 6 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(558, 'Pad 6 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(559, 'Pad 6 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(560, 'Pad 7 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(561, 'Pad 7 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(562, 'Pad 7 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(563, 'Pad 7 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(564, 'Pad 7 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(565, 'Pad 7 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(566, 'Pad 7 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(567, 'Pad 7 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(568, 'Pad 8 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(569, 'Pad 8 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(570, 'Pad 8 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(571, 'Pad 8 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(572, 'Pad 8 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(573, 'Pad 8 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(574, 'Pad 8 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(575, 'Pad 8 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(576, 'Pad 9 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(577, 'Pad 9 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(578, 'Pad 9 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(579, 'Pad 9 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(580, 'Pad 9 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(581, 'Pad 9 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(582, 'Pad 9 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(583, 'Pad 9 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(584, 'Pad 10 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(585, 'Pad 10 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(586, 'Pad 10 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(587, 'Pad 10 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(588, 'Pad 10 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(589, 'Pad 10 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(590, 'Pad 10 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(591, 'Pad 10 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(592, 'Pad 11 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(593, 'Pad 11 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(594, 'Pad 11 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(595, 'Pad 11 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(596, 'Pad 11 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(597, 'Pad 11 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(598, 'Pad 11 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(599, 'Pad 11 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(600, 'Pad 12 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(601, 'Pad 12 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(602, 'Pad 12 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(603, 'Pad 12 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(604, 'Pad 12 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(605, 'Pad 12 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(606, 'Pad 12 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(607, 'Pad 12 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(608, 'Pad 13 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(609, 'Pad 13 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(610, 'Pad 13 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(611, 'Pad 13 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(612, 'Pad 13 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(613, 'Pad 13 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(614, 'Pad 13 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(615, 'Pad 13 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(616, 'Pad 14 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(617, 'Pad 14 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(618, 'Pad 14 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(619, 'Pad 14 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(620, 'Pad 14 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(621, 'Pad 14 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(622, 'Pad 14 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(623, 'Pad 14 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(624, 'Pad 15 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(625, 'Pad 15 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(626, 'Pad 15 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(627, 'Pad 15 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(628, 'Pad 15 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(629, 'Pad 15 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(630, 'Pad 15 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(631, 'Pad 15 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(632, 'Pad 16 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(633, 'Pad 16 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(634, 'Pad 16 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(635, 'Pad 16 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(636, 'Pad 16 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(637, 'Pad 16 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(638, 'Pad 16 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(639, 'Pad 16 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(640, 'Pad 17 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(641, 'Pad 17 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(642, 'Pad 17 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(643, 'Pad 17 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(644, 'Pad 17 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(645, 'Pad 17 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(646, 'Pad 17 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(647, 'Pad 17 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(648, 'Pad 18 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(649, 'Pad 18 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(650, 'Pad 18 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(651, 'Pad 18 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(652, 'Pad 18 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(653, 'Pad 18 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(654, 'Pad 18 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(655, 'Pad 18 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(656, 'Pad 19 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(657, 'Pad 19 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(658, 'Pad 19 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(659, 'Pad 19 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(660, 'Pad 19 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(661, 'Pad 19 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(662, 'Pad 19 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(663, 'Pad 19 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(664, 'Pad 20 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(665, 'Pad 20 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(666, 'Pad 20 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(667, 'Pad 20 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(668, 'Pad 20 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(669, 'Pad 20 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(670, 'Pad 20 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(671, 'Pad 20 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(672, 'Pad 21 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(673, 'Pad 21 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(674, 'Pad 21 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(675, 'Pad 21 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(676, 'Pad 21 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(677, 'Pad 21 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(678, 'Pad 21 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(679, 'Pad 21 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(680, 'Pad 22 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(681, 'Pad 22 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(682, 'Pad 22 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(683, 'Pad 22 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(684, 'Pad 22 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(685, 'Pad 22 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(686, 'Pad 22 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(687, 'Pad 22 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(688, 'Pad 23 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(689, 'Pad 23 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(690, 'Pad 23 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(691, 'Pad 23 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(692, 'Pad 23 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(693, 'Pad 23 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(694, 'Pad 23 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(695, 'Pad 23 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(696, 'Pad 24 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(697, 'Pad 24 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(698, 'Pad 24 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(699, 'Pad 24 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(700, 'Pad 24 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(701, 'Pad 24 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(702, 'Pad 24 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(703, 'Pad 24 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(704, 'Pad 25 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(705, 'Pad 25 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(706, 'Pad 25 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(707, 'Pad 25 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(708, 'Pad 25 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(709, 'Pad 25 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(710, 'Pad 25 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(711, 'Pad 25 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(712, 'Pad 26 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(713, 'Pad 26 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(714, 'Pad 26 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(715, 'Pad 26 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(716, 'Pad 26 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(717, 'Pad 26 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(718, 'Pad 26 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(719, 'Pad 26 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(720, 'Pad 27 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(721, 'Pad 27 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(722, 'Pad 27 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(723, 'Pad 27 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(724, 'Pad 27 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(725, 'Pad 27 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(726, 'Pad 27 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(727, 'Pad 27 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(728, 'Pad 28 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(729, 'Pad 28 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(730, 'Pad 28 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(731, 'Pad 28 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(732, 'Pad 28 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(733, 'Pad 28 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(734, 'Pad 28 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(735, 'Pad 28 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(736, 'Pad 29 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(737, 'Pad 29 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(738, 'Pad 29 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(739, 'Pad 29 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(740, 'Pad 29 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(741, 'Pad 29 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(742, 'Pad 29 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(743, 'Pad 29 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(744, 'Pad 30 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(745, 'Pad 30 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(746, 'Pad 30 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(747, 'Pad 30 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(748, 'Pad 30 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(749, 'Pad 30 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(750, 'Pad 30 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(751, 'Pad 30 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(752, 'Pad 31 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(753, 'Pad 31 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(754, 'Pad 31 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(755, 'Pad 31 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(756, 'Pad 31 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(757, 'Pad 31 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(758, 'Pad 31 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(759, 'Pad 31 pan release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(760, 'Pad 32 volume attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(761, 'Pad 32 volume decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(762, 'Pad 32 volume sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(763, 'Pad 32 volume release', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(764, 'Pad 32 pan attack', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(765, 'Pad 32 pan decay', 0, '100%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(766, 'Pad 32 pan sustain', 0, '0%', False) )
plFPC.addParamToGroup('ALL', TnfxParameter(767, 'Pad 32 pan release', 0, '100%', False) )
# -----------------------------------------------------------------
#    Non Blank Params Count: 1024
# 
# Sample mapping of first 8 params to the USER1 and USER2 Knobs
# 
# plFPC.assignParameterToUserKnob(KM_USER1, 0, plFPC.PAD-1ParamFromOffset(0) ) # volume
# plFPC.assignParameterToUserKnob(KM_USER1, 1, plFPC.PAD-2ParamFromOffset(1) ) # volume
# plFPC.assignParameterToUserKnob(KM_USER1, 2, plFPC.PAD-3ParamFromOffset(2) ) # volume
# plFPC.assignParameterToUserKnob(KM_USER1, 3, plFPC.getParamFromOffset(3) ) # Pad 4 volume
# plFPC.assignParameterToUserKnob(KM_USER2, 0, plFPC.getParamFromOffset(4) ) # Pad 5 volume
# plFPC.assignParameterToUserKnob(KM_USER2, 1, plFPC.getParamFromOffset(5) ) # Pad 6 volume
# plFPC.assignParameterToUserKnob(KM_USER2, 2, plFPC.getParamFromOffset(6) ) # Pad 7 volume
# plFPC.assignParameterToUserKnob(KM_USER2, 3, plFPC.getParamFromOffset(7) ) # Pad 8 volume
# 
if(plFPC.Name not in KNOWN_PLUGINS.keys()):
    KNOWN_PLUGINS[plFPC.Name] = plFPC
# 
# add the following line (without the #) to the end of fireNFX_PluginDefs.py 
# from pluginFPC.py import plFPC
# 
# -----------------------------------------------------------------
<fireNFX_Classes.TnfxChannelPlugin object at 0x000000006637A340>
