#   PluginName:  Lounge Lizard EP-4
#   ParamCount:  4240
# -----------------------------------------------------------------
from fireNFX_Classes import TnfxParameter, TnfxChannelPlugin
plLoungeLizardEP4 = TnfxChannelPlugin('LoungeLizardEP-4')
plLoungeLizardEP4.addParamToGroup('Hammer', TnfxParameter(0, 'Stiffness', 0, '161Hz ', False) )
plLoungeLizardEP4.addParamToGroup('Hammer', TnfxParameter(1, 'Stiff Key', 0, '1.00 ', False) )
plLoungeLizardEP4.addParamToGroup('Hammer', TnfxParameter(2, 'Stiff Vel', 0, '0.20 ', False) )
plLoungeLizardEP4.addParamToGroup('Hammer', TnfxParameter(3, 'Force', 0, '-17.6dB ', False) )
plLoungeLizardEP4.addParamToGroup('Hammer', TnfxParameter(4, 'Force Key', 0, '0.11 ', False) )
plLoungeLizardEP4.addParamToGroup('Hammer', TnfxParameter(5, 'Force Vel', 0, '4.19 ', False) )
plLoungeLizardEP4.addParamToGroup('Hammer', TnfxParameter(6, 'Noise Amount', 0, '-18.8dB ', False) )
plLoungeLizardEP4.addParamToGroup('Hammer', TnfxParameter(7, 'Noise Pitch', 0, '300Hz ', False) )
plLoungeLizardEP4.addParamToGroup('Hammer', TnfxParameter(8, 'Noise Decay', 0, '78.3 ', False) )
plLoungeLizardEP4.addParamToGroup('Hammer', TnfxParameter(9, 'Noise Key', 0, '0.64 ', False) )
plLoungeLizardEP4.addParamToGroup('Fork', TnfxParameter(10, 'Tine', 0, '-34.0dB ', False) )
plLoungeLizardEP4.addParamToGroup('Fork', TnfxParameter(11, 'Tine Key', 0, '-0.58 ', False) )
plLoungeLizardEP4.addParamToGroup('Fork', TnfxParameter(12, 'Tine Decay', 0, '45.2% ', False) )
plLoungeLizardEP4.addParamToGroup('Fork', TnfxParameter(13, 'Tine Color', 0, '-0.42 ', False) )
plLoungeLizardEP4.addParamToGroup('Fork', TnfxParameter(14, 'Tone Bar', 0, '4.7dB ', False) )
plLoungeLizardEP4.addParamToGroup('Fork', TnfxParameter(15, 'Tone Decay', 0, '57.8% ', False) )
plLoungeLizardEP4.addParamToGroup('Fork', TnfxParameter(16, 'Release', 0, '1.22 ', False) )
plLoungeLizardEP4.addParamToGroup('Pickup', TnfxParameter(17, 'Type', 0, 'R ', False) )
plLoungeLizardEP4.addParamToGroup('Pickup', TnfxParameter(18, 'Input', 0, '-10.8dB ', False) )
plLoungeLizardEP4.addParamToGroup('Pickup', TnfxParameter(19, 'Symmetry', 0, '0.37 ', False) )
plLoungeLizardEP4.addParamToGroup('Pickup', TnfxParameter(20, 'Distance', 0, '0.18 ', False) )
plLoungeLizardEP4.addParamToGroup('Pickup', TnfxParameter(21, 'Output', 0, '6.8dB ', False) )
plLoungeLizardEP4.addParamToGroup('Pickup', TnfxParameter(22, 'Output Key', 0, '-0.36 ', False) )
plLoungeLizardEP4.addParamToGroup('Damper', TnfxParameter(23, 'Amount', 0, '38.3% ', False) )
plLoungeLizardEP4.addParamToGroup('Damper', TnfxParameter(24, 'Tone', 0, '103Hz ', False) )
plLoungeLizardEP4.addParamToGroup('Damper', TnfxParameter(25, 'Attack-Release', 0, '0.22 ', False) )
plLoungeLizardEP4.addParamToGroup('Tremolo', TnfxParameter(26, 'Shape', 0, 'Sqr ', False) )
plLoungeLizardEP4.addParamToGroup('Tremolo', TnfxParameter(27, 'Rate', 0, '1.31Hz ', False) )
plLoungeLizardEP4.addParamToGroup('Tremolo', TnfxParameter(28, 'Sync On', 0, 'Off ', False) )
plLoungeLizardEP4.addParamToGroup('Tremolo', TnfxParameter(29, 'Sync Rate', 0, '1 ', False) )
plLoungeLizardEP4.addParamToGroup('Tremolo', TnfxParameter(30, 'Mono', 0, 'Stereo ', False) )
plLoungeLizardEP4.addParamToGroup('Tremolo', TnfxParameter(31, 'Depth', 0, '35.0% ', False) )
plLoungeLizardEP4.addParamToGroup('Tremolo', TnfxParameter(32, 'On', 0, 'On ', False) )
plLoungeLizardEP4.addParamToGroup('Equalizer', TnfxParameter(33, 'Low Freq', 0, '209Hz ', False) )
plLoungeLizardEP4.addParamToGroup('Equalizer', TnfxParameter(34, 'Low Gain', 0, '3.6dB ', False) )
plLoungeLizardEP4.addParamToGroup('Equalizer', TnfxParameter(35, 'Low Mid Freq', 0, '1140Hz ', False) )
plLoungeLizardEP4.addParamToGroup('Equalizer', TnfxParameter(36, 'Low Mid Gain', 0, '-0.6dB ', False) )
plLoungeLizardEP4.addParamToGroup('Equalizer', TnfxParameter(37, 'Low Mid Q', 0, '5.00 ', False) )
plLoungeLizardEP4.addParamToGroup('Equalizer', TnfxParameter(38, 'High Mid Freq', 0, '1430Hz ', False) )
plLoungeLizardEP4.addParamToGroup('Equalizer', TnfxParameter(39, 'High Mid Gain', 0, '4.5dB ', False) )
plLoungeLizardEP4.addParamToGroup('Equalizer', TnfxParameter(40, 'High Mid Q', 0, '0.71 ', False) )
plLoungeLizardEP4.addParamToGroup('Equalizer', TnfxParameter(41, 'High Freq', 0, '3020Hz ', False) )
plLoungeLizardEP4.addParamToGroup('Equalizer', TnfxParameter(42, 'High Gain', 0, '8.4dB ', False) )
plLoungeLizardEP4.addParamToGroup('Equalizer', TnfxParameter(43, 'Side Chain', 0, 'Normal ', False) )
plLoungeLizardEP4.addParamToGroup('Equalizer', TnfxParameter(44, 'On', 0, 'On ', False) )
plLoungeLizardEP4.addParamToGroup('Compressor', TnfxParameter(45, 'Threshold', 0, '0.00dB ', False) )
plLoungeLizardEP4.addParamToGroup('Compressor', TnfxParameter(46, 'Ratio', 0, '2.78 ', False) )
plLoungeLizardEP4.addParamToGroup('Compressor', TnfxParameter(47, 'Attack', 0, '15.9ms ', False) )
plLoungeLizardEP4.addParamToGroup('Compressor', TnfxParameter(48, 'Release', 0, '40.1ms ', False) )
plLoungeLizardEP4.addParamToGroup('Compressor', TnfxParameter(49, 'Makeup', 0, '1.68dB ', False) )
plLoungeLizardEP4.addParamToGroup('Compressor', TnfxParameter(50, 'Pre', 0, 'Off ', False) )
plLoungeLizardEP4.addParamToGroup('Compressor', TnfxParameter(51, 'On', 0, 'Off ', False) )
plLoungeLizardEP4.addParamToGroup('Effect 1', TnfxParameter(52, 'On', 0, 'On ', False) )
plLoungeLizardEP4.addParamToGroup('Effect 1', TnfxParameter(53, 'Type', 0, 'Delay ', False) )
plLoungeLizardEP4.addParamToGroup('Effect 1', TnfxParameter(54, 'Param 1', 0, '0.18 ', False) )
plLoungeLizardEP4.addParamToGroup('Effect 1', TnfxParameter(55, 'Param 2', 0, '0.71 ', False) )
plLoungeLizardEP4.addParamToGroup('Effect 1', TnfxParameter(56, 'Param 3', 0, '0.00 ', False) )
plLoungeLizardEP4.addParamToGroup('Effect 1', TnfxParameter(57, 'Param 4', 0, '0.57 ', False) )
plLoungeLizardEP4.addParamToGroup('Effect 1', TnfxParameter(58, 'Param 5', 0, '0.39 ', False) )
plLoungeLizardEP4.addParamToGroup('Effect 1', TnfxParameter(59, 'Param 6', 0, '0.34 ', False) )
plLoungeLizardEP4.addParamToGroup('Effect 1', TnfxParameter(60, 'Param 7', 0, '0.62 ', False) )
plLoungeLizardEP4.addParamToGroup('Effect 1', TnfxParameter(61, 'Param 8', 0, '0.50 ', False) )
plLoungeLizardEP4.addParamToGroup('Effect 2', TnfxParameter(62, 'On', 0, 'Off ', False) )
plLoungeLizardEP4.addParamToGroup('Effect 2', TnfxParameter(63, 'Type', 0, 'Chorus ', False) )
plLoungeLizardEP4.addParamToGroup('Effect 2', TnfxParameter(64, 'Param 1', 0, '0.62 ', False) )
plLoungeLizardEP4.addParamToGroup('Effect 2', TnfxParameter(65, 'Param 2', 0, '1.00 ', False) )
plLoungeLizardEP4.addParamToGroup('Effect 2', TnfxParameter(66, 'Param 3', 0, '0.52 ', False) )
plLoungeLizardEP4.addParamToGroup('Effect 2', TnfxParameter(67, 'Param 4', 0, '0.00 ', False) )
plLoungeLizardEP4.addParamToGroup('Effect 2', TnfxParameter(68, 'Param 5', 0, '0.57 ', False) )
plLoungeLizardEP4.addParamToGroup('Effect 2', TnfxParameter(69, 'Param 6', 0, '0.29 ', False) )
plLoungeLizardEP4.addParamToGroup('Effect 2', TnfxParameter(70, 'Param 7', 0, '0.34 ', False) )
plLoungeLizardEP4.addParamToGroup('Effect 2', TnfxParameter(71, 'Param 8', 0, '0.50 ', False) )
plLoungeLizardEP4.addParamToGroup('Reverb', TnfxParameter(72, 'Size', 0, 'Hall ', False) )
plLoungeLizardEP4.addParamToGroup('Reverb', TnfxParameter(73, 'Decay', 0, '0.95 ', False) )
plLoungeLizardEP4.addParamToGroup('Reverb', TnfxParameter(74, 'Diffusion', 0, '62.2% ', False) )
plLoungeLizardEP4.addParamToGroup('Reverb', TnfxParameter(75, 'Low Damp', 0, '59.5Hz ', False) )
plLoungeLizardEP4.addParamToGroup('Reverb', TnfxParameter(76, 'High Damp', 0, '0.25 ', False) )
plLoungeLizardEP4.addParamToGroup('Reverb', TnfxParameter(77, 'Mix', 0, '6% ', False) )
plLoungeLizardEP4.addParamToGroup('Reverb', TnfxParameter(78, 'On', 0, 'On ', False) )
plLoungeLizardEP4.addParamToGroup('Global', TnfxParameter(79, 'Volume', 0, '0.0dB ', False) )
plLoungeLizardEP4.addParamToGroup('Global', TnfxParameter(80, 'Tune', 0, '0.00 ', False) )
plLoungeLizardEP4.addParamToGroup('Amp', TnfxParameter(81, 'Character', 0, 'None ', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4096, '#0 (Bank select MSB)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4097, '#1 (Modulation wheel)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4098, '#2 (Breath controller)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4099, '#3', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4100, '#4 (Foot controller)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4101, '#5 (Portamento time)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4102, '#6 (Data entry MSB)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4103, '#7 (Main volume)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4104, '#8 (Balance)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4105, '#9', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4106, '#10 (Pan)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4107, '#11 (Expression controller)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4108, '#12 (Control 1)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4109, '#13 (Control 2)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4110, '#14', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4111, '#15', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4112, '#16 (General purpose controller 1)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4113, '#17 (General purpose controller 2)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4114, '#18 (General purpose controller 3)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4115, '#19 (General purpose controller 4)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4116, '#20', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4117, '#21', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4118, '#22', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4119, '#23', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4120, '#24', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4121, '#25', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4122, '#26', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4123, '#27', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4124, '#28', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4125, '#29', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4126, '#30', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4127, '#31', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4128, '#32 (Bank select LSB)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4129, '#33 (Modulation wheel LSB)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4130, '#34 (Breath controller LSB)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4131, '#35', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4132, '#36 (Foot controller LSB)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4133, '#37 (Portamento time LSB)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4134, '#38 (Data entry LSB )', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4135, '#39 (Main volume LSB)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4136, '#40 (Balance LSB)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4137, '#41', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4138, '#42 (Pan LSB)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4139, '#43 (Expression controller LSB)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4140, '#44 (Control 1 LSB)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4141, '#45 (Control 2 LSB)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4142, '#46', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4143, '#47', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4144, '#48 (General purpose controller 1 LSB)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4145, '#49 (General purpose controller 2 LSB)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4146, '#50 (General purpose controller 3 LSB)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4147, '#51 (General purpose controller 4 LSB)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4148, '#52', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4149, '#53', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4150, '#54', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4151, '#55', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4152, '#56', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4153, '#57', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4154, '#58', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4155, '#59', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4156, '#60', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4157, '#61', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4158, '#62', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4159, '#63', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4160, '#64 (Damper pedal (sustain))', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4161, '#65 (Portamento)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4162, '#66 (Sostenuto)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4163, '#67 (Soft pedal)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4164, '#68 (Legato footswitch)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4165, '#69 (Hold 2)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4166, '#70 (Sound variation)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4167, '#71 (Harmonic content)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4168, '#72 (Release time)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4169, '#73 (Attack time)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4170, '#74 (Brightness)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4171, '#75 (Sound controller 6)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4172, '#76 (Sound controller 7)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4173, '#77 (Sound controller 8)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4174, '#78 (Sound controller 9)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4175, '#79 (Sound controller 10)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4176, '#80 (General purpose controller 5)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4177, '#81 (General purpose controller 6)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4178, '#82 (General purpose controller 7)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4179, '#83 (General purpose controller 8)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4180, '#84 (Portamento control)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4181, '#85', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4182, '#86', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4183, '#87', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4184, '#88', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4185, '#89', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4186, '#90', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4187, '#91 (Reverb depth)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4188, '#92 (Tremolo depth)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4189, '#93 (Chorus depth)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4190, '#94 (Celeste depth)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4191, '#95 (Phaser depth)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4192, '#96 (Data increment)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4193, '#97 (Data decrement)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4194, '#98 (NRPN LSB)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4195, '#99 (NRPN MSB)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4196, '#100 (RPN LSB)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4197, '#101 (RPN MSB)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4198, '#102', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4199, '#103', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4200, '#104', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4201, '#105', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4202, '#106', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4203, '#107', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4204, '#108', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4205, '#109', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4206, '#110', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4207, '#111', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4208, '#112', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4209, '#113', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4210, '#114', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4211, '#115', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4212, '#116', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4213, '#117', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4214, '#118', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4215, '#119', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4216, '#120 (All sound off)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4217, '#121 (Reset all controllers)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4218, '#122 (Local control on/off)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4219, '#123 (All notes off)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4220, '#124 (Omni mode off)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4221, '#125 (Omni mode on)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4222, '#126 (Mono mode on)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4223, '#127 (Poly mode on)', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4224, 'MIDI Channel 1 Aftertouch', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4225, 'MIDI Channel 2 Aftertouch', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4226, 'MIDI Channel 3 Aftertouch', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4227, 'MIDI Channel 4 Aftertouch', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4228, 'MIDI Channel 5 Aftertouch', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4229, 'MIDI Channel 6 Aftertouch', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4230, 'MIDI Channel 7 Aftertouch', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4231, 'MIDI Channel 8 Aftertouch', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4232, 'MIDI Channel 9 Aftertouch', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4233, 'MIDI Channel 10 Aftertouch', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4234, 'MIDI Channel 11 Aftertouch', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4235, 'MIDI Channel 12 Aftertouch', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4236, 'MIDI Channel 13 Aftertouch', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4237, 'MIDI Channel 14 Aftertouch', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4238, 'MIDI Channel 15 Aftertouch', 0, '', False) )
plLoungeLizardEP4.addParamToGroup('MIDI CC', TnfxParameter(4239, 'MIDI Channel 16 Aftertouch', 0, '', False) )
# -----------------------------------------------------------------
#    Non Blank Params Count: 452
None
